# Generated by Django 5.1.2 on 2024-12-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rezultat_certifikat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raspored',
            old_name='tecaj',
            new_name='raspored_tecaj',
        ),
        migrations.RenameField(
            model_name='raspored',
            old_name='vrijeme',
            new_name='raspored_vrijeme',
        ),
    ]
