# Generated by Django 5.1.2 on 2024-11-27 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boraviste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boraviste_naziv_mjesta', models.CharField(max_length=200)),
                ('boraviste_postanski_broj', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tecaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecaj_naziv', models.CharField(max_length=100)),
                ('tecaj_sadrzaj', models.TextField()),
                ('tecaj_broj_sati', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Razina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(choices=[('Viša', 'Viša'), ('Niža', 'Niža')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dan_u_tjednu', models.CharField(max_length=25)),
                ('vrijeme', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ucitelj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucitelj_ime', models.CharField(max_length=30)),
                ('ucitelj_prezime', models.CharField(max_length=30)),
                ('ucitelj_email', models.EmailField(max_length=254)),
                ('ucitelj_broj_sati', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Polaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polaznik_ime', models.CharField(max_length=25)),
                ('polaznik_prezime', models.CharField(max_length=50)),
                ('polaznik_oib', models.CharField(max_length=10)),
                ('polaznik_boraviste', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.boraviste')),
                ('polaznik_tecaj', models.ManyToManyField(to='main.tecaj')),
            ],
        ),
        migrations.AddField(
            model_name='tecaj',
            name='tecaj_razina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.razina'),
        ),
        migrations.CreateModel(
            name='Rezultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocjena', models.CharField(max_length=5)),
                ('polozen_tecaj', models.BooleanField(default=True)),
                ('polaznik', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.polaznik')),
                ('tecaj', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tecaj')),
            ],
        ),
        migrations.AddField(
            model_name='tecaj',
            name='tecaj_nositelj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ucitelj'),
        ),
        migrations.CreateModel(
            name='Raspored',
            fields=[
                ('tecaj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.tecaj')),
                ('vrijeme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.termin')),
            ],
        ),
    ]
