# Generated by Django 5.1.2 on 2024-11-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezultat',
            name='certifikat',
            field=models.BooleanField(default=False),
        ),
    ]
